# Generated by Django 5.2.13 on 2026-05-22 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femal'), ('U', 'Unknown')], default='U', max_length=1)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.person')),
                ('addresses', models.ManyToManyField(to='locationapp.address')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['created_date'],
            },
        ),
    ]
